# This file holds parameters for running a greedy algorithm that optimizes
#   a logic synthesis flow using ABC
# ============================================================================
# Organization: SCALE Lab @ Brown University
# Author: Abdelrahman Ibrahim <abdelrahman@brown.edu>
# License: MIT
# ===========================================================================

# change this to the abc binary path if the command is not recognized system-wide
abc_binary: abc 

# path of the design file in one of the accepted formats by ABC
design_file: my-design.blif

# library mapping
mapping:
  clock_period: 150   # in pico seconds
  library_file: my-library.lib

# add more optimization to the toolbo
optimizations:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -z
  - balance

# optimization objectives
optimize_for: delay     # options: (delay, area)
constraint_for: None    # options: (delay, area, None)
constraint_value: 0.0   # value of max delay or max area

# the directory to hold the playground the agent uses to practice
playground_dir: playground

# agent training parameters
episodes: 1000
iterations: 50