# This file holds parameters for running a greedy algorithm that optimizes
#   a logic synthesis flow using ABC
# ============================================================================
# Organization: SCALE Lab @ Brown University
# Author: Abdelrahman Hosny <abdelrahman_hosny@brown.edu>
# ===========================================================================

# change this to the abc binary path if the command is not recognized system-wide
abc_binary: yosys-abc
yosys_binary: yosys

# path of the design file in one of the accepted formats by ABC
design_file: /Users/abdelrahman/Desktop/benchmarks/arithmetic/adder.v

# library mapping
mapping:
  clock_period: 150   # in pico seconds
  library_file: /Users/abdelrahman/Desktop/benchmarks/asap7.lib

# add more optimization to the toolbo
optimizations:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -z
  - balance

# the directory to hold the playground the agent uses to practice
playground_dir: playground

# agent training parameters
episodes: 100
iterations: 50
model_dir: /tmp/brain   # must be absolute path